service:
  name: UiService
  header: services/ui/ui_service.h

includes:
  - "services/ui/ui_context.h"
  - "services/ui/widget_list.h"
  - "services/render/backend/common/render_composition.h"
  - "services/ui/model_style.h"

components:
  - name: UiRuntimeComponent
    fields:
      - { name: "ui", type: "UiContext*" }
      - { name: "widgets", type: "WidgetArray" }
      - { name: "display_list", type: "DisplayList" }

  - name: ModelComponent
    fields:
      - { name: "model", type: "Model*" }