service:
  name: RenderRuntimeService
  header: services/render/runtime/render_runtime_service.h

includes:
  - "services/render/backend/common/render_context.h"
  - "services/assets/assets.h"
  - "services/ui/ui_context.h"
  - "services/ui/widget_list.h"
  - "services/render/backend/common/render_composition.h"
  - "services/ui/model_style.h"

components:
  - name: RenderReadyComponent
    fields:
      - { name: "render", type: "RenderRuntimeContext*" }
      - { name: "assets", type: "const Assets*" }
      - { name: "ui", type: "UiContext*" }
      - { name: "widgets", type: "WidgetArray" }
      - { name: "display_list", type: "DisplayList" }
      - { name: "model", type: "Model*" }
      - { name: "ready", type: "bool" }