service:
  name: AssetsService
  header: services/assets/assets_service.h
  runtime: true

context:
  - { name: assets, type: Assets }

components:
  - name: AssetsComponent
    fields:
      - { name: "assets", type: "Assets*" }