service:
  name: SceneService
  header: services/scene/scene_service.h

includes:
  - "services/scene/cad_scene.h"

components:
  - name: SceneComponent
    fields:
      - { name: "scene", type: "Scene*" }
      - { name: "path", type: "const char*" }
